import React from "react";
import type {Metadata} from "next";
import localFont from "next/font/local";
import {Montserrat} from "next/font/google";
import {ThemeProvider} from "@/components/theme-provider";
import {AuthProvider} from "@/app/auth-provider";
import "./globals.css";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});
const montserrat = Montserrat({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                             children,
                                         }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <AuthProvider>
            <html lang="en">
            <body
                className={`${montserrat.className} ${geistSans.variable} ${geistMono.variable} antialiased font-medium`}
            >
            <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
            >{children}</ThemeProvider>
            </body>
            </html>
        </AuthProvider>
    );
}
